#!/bin/bash
#
#	miniaturas para openscad



E=$(echo $2 | sed 's/^file:\/\///g')
EXT="$( echo $E | sed 's/^.*\.//g')"
if [ "$EXT" == "stl" ]; then
	T=$(mktemp --suffix=.scad)
	echo "import(\"$E\");" > $T
	E=$T
fi
/usr/bin/openscad --preview -o $(echo $1 | sed 's/^file:\/\///g') $E
convert $(echo $1 | sed 's/^file:\/\///g') \
-trim \
-transparent '#ffffe5' \
-resize 196x196 \
$(echo $1 | sed 's/^file:\/\///g')
rm $T 2> /dev/null
